version: 2
jobs:
  verify-outputs:
    docker: 
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - run: 
          name: Build All
          command: yarn build:all
      - run:
          name: Verify Artifacts
          command: yarn test