version: 2
jobs:
    build:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - run:
                  name: Prettier Check
                  command: |
                      yarn install
                      yarn prettier:check
            - run:
                  name: Build All
                  command: yarn build:all
            - run:
                  name: Verify Artifacts
                  command: yarn test
            -   persist_to_workspace:
                    root: .
                    paths:
                        - react/dist
                        - react-native/dist

    publish:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            -   attach_workspace:
                    at: .
            -   run:
                    name: Authenticate with registry
                    command: |
                        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                        echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc            
            -   run:
                    name: Publish @pxblue/angular-themes
                    command:  |
                        cd angular
                        yarn publish:package -b $CIRCLE_BRANCH
            -   run:
                    name: Publish @pxblue/react-themes
                    command:  |
                        cd react
                        yarn publish:package -b $CIRCLE_BRANCH
            -   run:
                    name: Publish @pxblue/react-native-themes
                    command:  |
                        cd react-native
                        yarn publish:package -b $CIRCLE_BRANCH
            -   run:
                    name: Publish @pxblue/storybook-themes
                    command:  |
                        cd storybook
                        yarn publish:package -b $CIRCLE_BRANCH
workflows:
    version: 2
    themes:
        jobs:
            - build
            - publish:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - dev
